syntax = "proto3";
package oro;

// NOTE NOTE NOTE NOTE
// NOTE NOTE NOTE NOTE
//
// If you change this file, Python code needs to be updated! Use the `protoc`
// compiler, running the script `agent/protobuf-compile.py`.
// (Javscript code picks up the changes automatically)
//
// NOTE NOTE NOTE NOTE
// NOTE NOTE NOTE NOTE

//
// Disk usage message. Used to send disk data within a SystemStatsMessage.
//
message DiskUsageMessage {
  string volume_id = 1;
  float usage_percentage = 2;
}

//
// Network stats message. Used to send network interfaces data within a
// SystemStatsMessage.
//
message NetworkStatsMessage {
  string interface_id = 1;
  int64 tx = 2;
  int64 rx = 3;
}

//
// Message in /r/+/system/stats with various
// system statistics from a robot.
//
message SystemStatsMessage {
  // Client timestamp (milliseconds) this info was captured
  int64 timestamp = 1;

  // Duration of this reported period
  float elapsed_seconds = 2;

  // CPU load:
  // average in this period, percentage [0.0, 1.0]
  float cpu_load_percentage = 3;

  // Network stats, transfers in/out since last reported
  string network_interface = 4;
  int64 total_tx = 5;
  int64 total_rx = 6;
  int64 agent_tx = 7;
  int64 agent_rx = 8;

  // Disk usage:
  // total usage percentage: [0.0, 1.0]
  float hdd_usage_percentage = 9;
  // usage by Agent, in Mb
  float agent_hdd_usage_mb = 10;
  // usage by Agent, percentage: [0.0, 1.0]
  float agent_hdd_usage_percentage = 11;

  // battery fields (battery_voltage, battery_percent, battery_ts): now removed
  // Just in case do NOT reuse the following IDs: 12, 13, 14.

  repeated DiskUsageMessage optional_disks_data = 15;
  repeated NetworkStatsMessage optional_network_interfaces_data = 16;

  // RAM usage, percentage [0.0, 1.0]
  float ram_usage_percentage = 17;
}

//
// Message in /r/+/ros/odometry/data with odometry information.
//
message OdometryDataMessage {
  // Timestamp (milliseconds) when the agentlet started
  // accumulating odometry
  int64 ts_start = 1;

  // Timestamp (milliseconds) of the last time odometry
  // accumulator was updated
  int64 ts = 2;

  // Accumulated displacement (meters)
  float linear_distance = 3;

  // Accumulated rotation (radians)
  float angular_distance = 4;

  // Linear speed (m/s)
  float linear_speed = 5;

  // Angular speed (rad/s)
  float angular_speed = 6;

  // Sanity Check: Current speed info is in the message
  bool speed_available = 7;
}

//
// Data point from a ros path.
// (Not a mqtt message)
//
message PathPoint {
  // X coordinate
  float x = 1;
  // Y coordinate
  float y = 2;
}

// Single path element, built from PathPoints.
// (Not an mqtt message)
message RobotPath {
  // List of points in this path
  repeated PathPoint points = 1;
  // Time this event data was generated
  int64 ts = 2;
  // Id of the path being sent, same as the one received on the
  // config
  string path_id = 3;
}

//
// Message in r/+/ros/loc/path with current paths information.
//
message PathDataMessage {
  // List of points in this path
  // NOTE: deprecated for agentVer >= 1.20.0
  repeated PathPoint points = 1;
  // Time this event data was generated
  int64 ts = 2;
  // Paths information
  repeated RobotPath paths = 3;
}

//
// Message with a map data. Used for maps and costmaps
// (r/+/ros/loc/map and r/+/ros/loc/costmap)
// Data encoded in PNG format in the bytes field.
// Note that the format of the data (grayscale, color, with transparency)
// is not defined in the message - it should be decoded from the PNG,
// or known by the receiver (e.g. costmaps have transparency).
//
message MapMessage {
  // Width, pixels
  uint32 width = 1;
  // Height, pixels
  uint32 height = 2;
  // Binary data, PNG format
  bytes pixels = 3;
  // X position
  float x = 4;
  // Y position
  float y = 5;
  // Yaw, orientation, in radians
  float theta = 6;
  // Resolution (m/cell), from ros
  float resolution = 7;
  // Time this event data was generated
  int64 ts = 8;
  // ROS topic or another identifier this map corresponds to
  string label = 9;
  // Python hash over the map's occupancy grid data tuple
  int64 data_hash = 10;
}

// Used by ingest to request a map to be loaded from the robot to the cloud
// Used in (r/<robot_id>/ros/loc/mapreq)
message MapRequest {
  // ROS topic or another identifier this map corresponds to
  string label = 9;
  // Python hash over the map's occupancy grid data tuple
  int64 data_hash = 10;
}

// Represents the frame of refrence. These frames are in simplified format
// and the specific ROS (or other navigation system) frame ID is translated
// by the agent based on its configuration and state.
enum Nav2DWaypointFrame {
  // Default value: unspecified
  UNKNOWN = 0;
  // Map frame
  MAP = 1;
  // Robot frame
  ROBOT = 2;
}

// Waypoint location for navigation goal messages
// Translation and rotation values are in reference of the provided
// frame.
message Nav2DWaypointMessage {
  // Optional: robot frame. This is only used if this message
  // is used stand-alone.
  // When this message is used as part of Nav2DPathMessage, the
  // frame of the Nav2DPathMessage is always used.
  Nav2DWaypointFrame frame = 1;
  // X position in meters
  float x = 2;
  // Y position in meters
  float y = 3;
  // Yaw, orientation, in radians
  float theta = 4;
}

// Waypoint navigation message, used for waypoint navigation.
// Defined originally for "teleop nudge".
// Used in (r/<robot_id>/ros/nav/goal_path)
message Nav2DPathMessage {
  // Reference frame for all points in this path
  Nav2DWaypointFrame frame = 1;
  // Timestamp of the last camera image or robot position seen by the
  // user when submitting this message, in milliseconds.
  int64 ts_hint = 2;
  // Waypoint list in order of execution
  repeated Nav2DWaypointMessage waypoints = 3;
}

//
// Message in r/+/alert/out with an alert information.
//
message AlertMessage {
  // Timestamp (milliseconds) when the agentlet sent the alert
  int64 ts = 1;

  // Component Id corresponding to what the alert points to
  string component_id = 2;

  // status (new or cleared)
  string status = 3;

  // event level (warning, error, fatal)
  string level = 4;

  // event name
  string name = 5;

  // event message
  string message = 6;
}

//
// Echo message
//
message Echo {
  //Agent timestamp in ms
  int64 time_stamp = 1;
  //Message topic
  string topic = 2;
  //Payload which can be either a byte or string payload.
  oneof payload {
    string string_payload = 3;
    bytes byte_payload = 4;
  }
}

//
// Message in r/+/ros/rosbag/update with updated information on a rosbag.
//
message RosbagUpdateMessage {
  // Name of the rosbag file stored in local/rosbags
  string name = 1;

  // Local storage status (stored in robot or not)
  bool stored_in_robot = 2;

  // Uploading status
  bool uploading_to_cloud = 3;

  // URL of the uploaded file (url string if uploaded, empty string if not)
  string url = 4;

  // Timestamp (milliseconds)
  int64 ts = 5;
}

//
// Laser points data.
// (Not a mqtt message)
//
message LaserMessage {
  string name = 1;

  // List of laser range values. This is our own encoded object
  // (so infinite values take less space)
  FloatingPointList ranges = 2;
}

//
// List of floating point numbers (mixed with infinite values).
//
// Validations:
//    - `sum(runs)==N`; where N is the original length of list
//    - `runs[i]>0 for every i>0`; ie. no "null runs", except the first one if
//      list does not start with inf)
//    - `sum(runs[1::2])==len(values)`, ie. the number of values listed
//      (non infinite numbers) equals the total length of non-inf runs.
//
// (Not a mqtt message)
//
message FloatingPointList {
  // Length of each sequence of consecutive infinite and non-infinite elements.
  // Odd positions are number of infinite values in this run;
  // while Even positions are number of non-infinite values in this run (ie.
  // those elements in values field).
  repeated uint32 runs = 1;

  // List of deltas. Each range r_i in this list represents the number
  // delta_i = (r_i / 10^precision), and the actual range is
  // r_i = r_j + delta_i ; where j is the last _non infinite_ range (or 0
  // of there was no previous value).
  repeated float values = 2;
}

//
// Message in r/+/ros/loc/data2 with updated information on a laser.
//
message LocationAndPoseMessage {
  // Timestamp (milliseconds)
  int64 ts = 1;

  // Robot pose
  float pos_x = 2;
  float pos_y = 3;
  float yaw = 4;

  // Lasers
  repeated LaserMessage lasers = 5;
}

//
// Message in r/+/ros/loc/pose with updated information on robot pose(s).
// This is an alternative to LocationAndPoseMessage, sent from PoseAgentlet
// instead of LocalizationAgentlet.
//
message PoseMessage {
  repeated PoseMessageData poses = 1;
}

//
// Data element for PoseMessage - it can contain multiple of these 2D poses
//
message PoseMessageData {
  // Timestamp (milliseconds)
  int64 ts = 1;

  // Robot pose
  float pos_x = 2;
  float pos_y = 3;
  float yaw = 4;

  // The following field is RESERVED for now to identify the 'source' or
  // 'type' of this pose, if other than robot-in-map pose. Still unused and
  // pending design - to be decided if both frames should be sent, or
  // just one, or some id of this pose "type"
  // string type = 5;
}

// Message with camera images in r/+/ros/camera2
// Data encoded in JPG format in the bytes field.
//
message CameraMessage {
  // Camera id
  string camera_id = 1;

  // Width, pixels
  uint32 width = 2;

  // Height, pixels
  uint32 height = 3;

  // Binary data, JPG format
  bytes image = 4;

  // Time this event data was generated
  int64 ts = 5;
}

// Message in logfiles_update topic
//
message RobotFileData {
  // Name of the rosbag file stored in local/rosbags
  string name = 1;

  // Local storage status (stored in robot or not)
  bool stored_in_robot = 2;

  // Uploading status
  bool uploading_to_cloud = 3;

  // URL of the uploaded file (url string if uploaded, empty string if not)
  string url = 4;

  // Timestamp (milliseconds)
  int64 ts = 5;

  // File size (Bytes)
  int64 size = 6;

  // File type (log, rosbag, etc)
  string type = 7;
}

// Message in logfiles_update topic
//
message RobotFilesUpdateMessage {
  // Array  of RobotFileData
  repeated RobotFileData artifacts = 1;

  // Timestamp (milliseconds)
  int64 ts = 2;
}

// Key-value elements
message KeyValueCustomElement {
  string key = 1;
  string value = 2;
  int64 ts = 3;
}

// Array of key value pairs to be sent as custom data
message KeyValuePairs {
  repeated KeyValueCustomElement pairs = 1;
}

// Key-Value pair obtained from ROS Diagnostics
message DiagnosticsMessage {
  // Name of the custom data source to be displayed as element key
  string label = 1;
  // Key value pair data obtained from ROS diagnostics
  string key = 2;
  string value = 3;
}

// Text file data (extended, includes both content and size details)
message TextFileMessage {
  bytes data = 1;
  int32 blob_offset = 2; // 0 if head or total_file_size - blob_size if tail
  int32 blob_size = 3; // size in bytes of the file_content sent
  int32 total_file_size = 4; // total file size in bytes
}

// Message with custom data messages in r/+/custom
message CustomDataMessage {
  // ID of the custom data element
  string custom_field = 1;

  // Custom element. It can be of any of the indicated types
  // (only key-value supported for now)
  oneof payload {
    KeyValuePairs key_value_payload = 2;
    bytes image_payload = 3;
    // TODO (Flor_Grosso): this field is deprecated and replaced by
    // text_file_payload_2 for agent versions higher than 1.5.0.
    // Consider removing it when possible.
    bytes text_file_payload = 4;
    DiagnosticsMessage diagnostics_payload = 5;
    TextFileMessage text_file_payload_2 = 6;
  }
}

//
// Message with rostopic monitoring updates
//
message TopicMonitorMessage {
  // Topic name
  string name = 1;
  // Flag to indicate that rate will be sent
  bool has_rate = 2;
  // Topic rate [mHz]
  int32 rate = 3;
}

//
// Message with rosparam monitoring updates
//
message ParamMonitorMessage {
  // Parameter name
  string name = 1;
  // Parameter value
  string value = 2;
}

//
// Message with rosnode monitoring updates
//
message NodeMonitorMessage {
  // Node name
  string name = 1;
  // Flag to indicate that ping response will be sent
  bool has_ping_response = 2;
  // Ping response
  bool pinged = 3;
}

//
// Message with rosservice monitoring updates
// NOTE (Flor_Grosso): fields need to be defined
//
message ServiceMonitorMessage {
  // Service name
  string name = 1;
}

//
// Message with ros monitor messages in r/+/ros/monitor/update
//
message RosMonitorMessage {
  int64 ts = 1;
  // ROS Master status (0 or 1)
  int32 master_status = 2;
  // Array of topic monitor messages
  repeated TopicMonitorMessage topics_update = 3;
  // Array of param monitor messages
  repeated ParamMonitorMessage params_update = 4;
  // Array of node monitor messages
  repeated NodeMonitorMessage nodes_update = 5;
  // Array of service monitor messages
  repeated ServiceMonitorMessage services_update = 6;
}

//
// Message with rosout messages in r/+/ros/rosout2
//
message RosOutMessage {
  int64 ts = 1;
  // Concatenated rosout messages, compressed
  bytes log = 2;
  // Flag indicated whether there are missing messages or not
  bool has_skipped_msgs = 3;
}

//
// Message with ros custom command to publish to (inorbit/oro)/custom_command
// (client -> agent)
//
message CustomCommandRosMessage {
  int64 ts = 1;
  string cmd = 2;
}

//
// Message with custom script to execute in /custom_command/script/command
// (server -> agent)
//
message CustomScriptCommandMessage {
  int64 ts = 1;
  // Name of the script to execute
  string file_name = 2;
  // Array of strings with ordered arguments flags and options
  repeated string arg_options = 3;
  // File content, in case the script to execute comes from the client
  string script_contents = 4;
  // Flag to indicate that the script needs to be executed immediately
  bool run = 5;
  // Unique-by-robot string to identify the script execution instance
  string execution_id = 6;
}

//
// Message with custom script execution updates in /custom_command/script/status
// (agent -> server)
//
message CustomScriptStatusMessage {
  int64 ts = 1;
  // Name of the script executed
  string file_name = 2;
  // Status flag (To be started, Running, Finished, Aborted)
  string execution_status = 3;
  // Execution exit code
  string return_code = 4;
  // String with stout message
  string stdout = 5;
  // String with stderr message
  string stderr = 6;
  // Unique-by-robot string to identify the script execution instance
  string execution_id = 7;
  // String with details on the status flag
  string execution_status_details = 8;
}

//
// Teleop GO command
// sent through topic: r/<robot_id>/ros/teleop/go
//
message TeleopGoCommand {
  // Timestamp of the last camera image or robot position seen by the
  // user when submitting this message, in milliseconds.
  int64 ts_hint = 1;
  float linear_velocity = 2;
  float angular_velocity = 3;
}

//
// Generic key value pair message
//
// NOTE: this is for nested key/value pairs. Not to be used for now, added for a future implementation.
message KeyValueMessage {
  string key = 1;
  string value = 2;
}

//
// Diagnostics data element. It matches a certain component name.
//
message RosDiagnosticsField {
  string name = 1;
  int32 level = 2;
  string msg = 3;
  repeated KeyValueMessage key_values = 4;
  bool has_level = 5;
}

//
// Ros diagnostics message. It is composed by nested diagnostics data
// fields and the timestamp of last update.
// sent through topic: r/<robot_id>/ros/diagnostics2
//
message RosDiagnosticsMessage {
  int64 ts = 1;
  repeated RosDiagnosticsField fields = 2;
}

//
// Ros diagnostics status message. It contains the result of merging
// levels for all diagnostics components and the timestamp of last
// diagnostics update.
// Sent through topic: r/<robot_id>/ros/diagnostics/status
//
message RosDiagnosticsStatusMessage {
  int64 ts = 1;
  int32 status = 2;
  // Flag to indicate that status will be sent
  bool has_status = 3;
}

//
// Messages for module state options
//
// Currently docyumented in https://docs.google.com/document/d/1NF_56a5CYkrDLqIeZ4oOnxzOyorkiTrYtO1pI2KuiLQ/edit#heading=h.fgr9xaf7wq83
//
// Sent by the agent to the server via r/<robot_id>/modules/state_options
//
// Main object is ModuleStateOptionsMessage below
//
message StateOptions {
  string state_name = 1;
  repeated string values = 2;
}

message ModuleStateOptionsMessage {
  string module_name = 1;
  repeated StateOptions state_options = 2;
}
