/**
 * Copyright 2026 InOrbit, Inc.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/**
 * Map base component.
 * Creates a context and passes the map to its children so that
 * they can modify it.
 */
import React, { useRef, useState, useEffect, useMemo } from 'react';
import proj4 from 'proj4';
import OlMap from 'ol/Map';
import OlView from 'ol/View';
import { register } from 'ol/proj/proj4';
import { toLonLat } from 'ol/proj';
import Projection from 'ol/proj/Projection';
import MouseWheelZoom from 'ol/interaction/MouseWheelZoom';
import { defaults } from 'ol/control';
import PropTypes from 'prop-types';
import { isEqual } from 'lodash';
// Oro Modules
import './map.css';
import { useLocalizationWidget } from '../../../contexts/LocalizationWidgetContext';
import { useActiveInteraction } from '../../../contexts/ActiveInteractionContext';
import { EMPTY_FUNCTION, LOCALIZATION_MAP_TYPES } from '../../../../../shared/constants';

export const MapContext = React.createContext();
export const MapProjection = React.createContext();

// Property names for map elements (shared with some layers)
const FEATURE_PROPERTY_ANNOTATION_UNIQUE_ID = 'annotationQualifiedId';

/*
  String to identify if feature is a zone, by looking at the ID
  generated by ingest -> `trafficzone-${zoneId}-${randomId()}`;
*/
const TRAFFIC_ZONE_IDENTIFIER = 'trafficzone';

/**
 * Wrapper that will defer execution of a provided callback function.
 *
 * It returns a new callback function that will delay executing until
 * the function is not called for a given delayPeriodMs (default = 750ms).
 */
const delayCall = (cb, options = {}) => {
  const { delayPeriodMs = 750 } = options;
  let timer;

  const doCall = (params) => {
    timer = undefined;
    cb(params);
  };

  return (params = {}) => {
    timer && clearTimeout(timer);
    timer = setTimeout(() => doCall(params), delayPeriodMs);
  };
};

/**
 * Transforms a robot pose to latitude/longitude coordinates.
 * @param {object} poseData - Robot pose with x, y coordinates in the map projection.
 * @param {string|Projection} mapProjection - The current map's OL projection.
 * @returns {Object} An object containing { latitude, longitude }.
 */
const transformPoseToLatLng = (poseData, mapProjection) => {
  const { x, y } = poseData;
  const poseCoordinate = [x, y];
  const latLon = toLonLat(poseCoordinate, mapProjection);
  return { latitude: latLon[1], longitude: latLon[0] };
};

/**
 * onPanStart - callback with no parameters, called whenever the user starts a map panning action
 * onPanEnd - callback with a single 'center' parameter, called when the user ends map panning
 * onZoomChange - called whenever there is a change in the zoom level
 *
 * type - "image" (metric with 0,0 in the map coordinate frame)
 *        "navsat" (geocentric, UTM with center in a specific zone)
 * viewParams - view projection details. In the case of "navsat", it includes the utmZone
 */
const Map = ({
  type = LOCALIZATION_MAP_TYPES.IMAGE,
  viewParams = {},
  children,
  zoom,
  center,
  dataTest,
  onFeatureHover = EMPTY_FUNCTION,
  onPanStart = EMPTY_FUNCTION,
  onPanEnd = EMPTY_FUNCTION,
  onZoomChange = EMPTY_FUNCTION,
  onRobotClick,
  selectedRobotPose,
  selectedRobotId,
  variant
}) => {
  const mapRef = useRef();
  const [map, setMap] = useState(null);
  // autoFitRef lets child layers (e.g. MapImageLayer) register a fit function
  // without mutating the OL map object directly
  const autoFitRef = useRef(null);
  const {
    setSelectedAnnotationQualifiedId, selectedAnnotationQualifiedId
  } = useLocalizationWidget();
  const { data: interactionData, activeInteraction } = useActiveInteraction();
  const {
    zoneData,
    createNewZone,
    modified
  } = interactionData || {};
  const { utmZone } = viewParams;

  const mapProjection = useMemo(() => {
    if (type == LOCALIZATION_MAP_TYPES.IMAGE) {
      // We will be using the map in meters, corresponding to the 'map' frame used in ROS
      // We need to define a maximum extent in meters. For now hardcoded to 100 meters in
      // each direction
      // TODO: Calculate a good extent for the map
      const extent = [-800, -800, 800, 800];
      return new Projection({
        code: 'frame-map',
        units: 'm',
        extent,
      });
    } else if (type == LOCALIZATION_MAP_TYPES.NAV_SAT) {
      const projName = `utm-${utmZone}`;
      const projString = `+proj=utm +zone=${utmZone} +units=m +no_defs`;
      // TODO: Optimize this. See if we can avoid importing the 'proj4' package
      // and also if we shouldn't move this to a higher-level context or global singleton
      // so that we create and register projections only if they haven't been created yet
      proj4.defs(projName, projString);
      register(proj4);
      return projName;
    } else {
      throw new Error(`Unknown map type: ${type}`);
    }
  }, [type, utmZone]);

  // Initialize map on first render
  useEffect(() => {
    const mapObject = new OlMap({
      target: mapRef.current,
      // NOTE: Removing this at construction times creates a problem on
      // MapImageLayer, causing the custom transformation to go wrong
      view: new OlView({
        zoom,
        center,
        projection: mapProjection
      }),
      layers: [],
      controls: defaults({
        zoom: false,
        rotate: false,
        attribution: false
      })
    });
    // Get the MouseWheelZoom interaction from the default interactions in the Map
    // and set it to center on the current center and not on the mouse position
    const interactions = mapObject.getInteractions();
    const zoomI = interactions.getArray().find(i => i instanceof MouseWheelZoom);
    zoomI.setMouseAnchor(false);

    setMap(mapObject);

    // Watch for container size changes and update map accordingly
    // Even though OL listens to window resize, it doesn't trigger when the container goes into
    // fullscreen.
    const resizeObserver = new ResizeObserver(() => {
      mapObject.updateSize();
    });
    resizeObserver.observe(mapRef.current);

    // On unmount, remove the map and cleanup
    return () => {
      if (resizeObserver) {
        resizeObserver.disconnect();
      }
      mapObject.setTarget(undefined);
    };
  }, []);

  // Allow hover effect when Time Control is not playing
  useEffect(() => {
    if (!map) return;
    let pointerMoveFn;
    if (onFeatureHover) {
      pointerMoveFn = (evt) => {
        const pixel = map.getEventPixel(evt.originalEvent);
        const feature = map.forEachFeatureAtPixel(pixel, ft => ft);
        feature && onFeatureHover(feature);
      };
      map.on('pointermove', pointerMoveFn);
    }
    return () => {
      pointerMoveFn && map.un('pointermove', pointerMoveFn);
    };
  }, [onFeatureHover, map]);

  useEffect(() => {
    if (!map) return;
    const view = new OlView({
      zoom, center, projection: mapProjection
    });
    map.setView(view);
    // If no center and zoom are provided as props, we need to reset them
    // when we change the view, otherwise it doesn't know how to present itself
    if (!center && !zoom) {
      if (autoFitRef.current) {
        autoFitRef.current();
      } else {
        map.getView().setZoom(19);
        map.getView().setCenter([0, 0]);
      }
    }
  }, [map, mapProjection]);

  // Create and memoize a delayed-firing callback function for zoom updates
  const callZoomChange = useMemo(() => delayCall(onZoomChange), []);

  // Surface zoom and pan actions as callbacks
  useEffect(() => {
    if (!map) return undefined;
    const changeResolutionFn = () => {
      callZoomChange({ zoom: map.getView().getZoom() });
    };
    const pointerDragFn = () => {
      onPanStart && onPanStart();
    };
    const moveEndFn = () => {
      const newCenter = map.getView().getCenter();
      onPanEnd && onPanEnd({ newCenter });
    };
    const clickFn = (evt) => {
      // Check if the clicked feature has a robotId or a annotationId property
      const robotId = map.forEachFeatureAtPixel(evt.pixel, clickFeature => (
        clickFeature.get('robotId')
      ));
      const annotationQualifiedId = map.forEachFeatureAtPixel(evt.pixel, clickFeature => (
        clickFeature.get(FEATURE_PROPERTY_ANNOTATION_UNIQUE_ID)
      ));
      if (robotId && onRobotClick && !createNewZone && !modified) {
        onRobotClick(robotId);
      }
      if (annotationQualifiedId) {
        setSelectedAnnotationQualifiedId(
          isEqual(selectedAnnotationQualifiedId, annotationQualifiedId)
            ? null : annotationQualifiedId
        );
      }
    };
    map.getView().on('change:resolution', changeResolutionFn);
    map.on('pointerdrag', pointerDragFn);
    map.on('moveend', moveEndFn);
    map.on('singleclick', clickFn);
    return () => {
      map.getView().un('change:resolution', changeResolutionFn);
      map.un('pointerdrag', pointerDragFn);
      map.un('moveend', moveEndFn);
      map.un('singleclick', clickFn);
    };
  }, [
    map,
    modified,
    mapProjection,
    activeInteraction,
    onRobotClick,
    zoneData,
    createNewZone,
    setSelectedAnnotationQualifiedId,
    onPanStart,
    onPanEnd
  ]);

  // Zoom change handler
  useEffect(() => {
    if (!map || zoom === undefined) return;
    map.getView().setZoom(zoom);
  }, [zoom, map]);

  // Center change handler
  useEffect(() => {
    if (!map) return;
    if (!center) return;
    map.getView().setCenter(center);
  }, [center, map]);

  // Create objects to pass as props from context values (simply so the props is not a new object
  // every time)
  const mapProjectionContextValue = useMemo(() => ({ mapProjection }), [mapProjection]);
  // autoFitRef is a stable ref (never changes identity), so it is intentionally omitted from deps
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const mapContextValue = useMemo(() => ({ map, autoFitRef }), [map]);
  // Calculates latitude and longitude values
  const gpsFix = useMemo(() => (
    selectedRobotPose
    && type == LOCALIZATION_MAP_TYPES.NAV_SAT
    && transformPoseToLatLng(selectedRobotPose, mapProjection)
  ), [selectedRobotPose, mapProjection]);

  return (
    <MapProjection.Provider value={mapProjectionContextValue}>
      <MapContext.Provider value={mapContextValue}>
        <div ref={mapRef} className="ol-map" data-test={dataTest || 'ol-map'}>
          {children}

        </div>
      </MapContext.Provider>
    </MapProjection.Provider>
  );
};

Map.propTypes = {
  // Type of map (indoors image based, or outdoor GPS based)
  // Can take values from constants.LOCALIZATION_MAP_TYPES
  type: PropTypes.string,
  // Parameters necessary to create the view, dependent on the
  // map type
  viewParams: PropTypes.object,
  // Map image children which has to be rendered in OL
  children: PropTypes.oneOfType([PropTypes.object, PropTypes.array]),
  // zoom level for the map view
  zoom: PropTypes.number,
  // boolean that enables actions after hovering features on the map
  onFeatureHover: PropTypes.func,
  onRobotClick: PropTypes.func,
  // coord point that marks the map center
  center: PropTypes.array,
  // callback for zoom changes
  onZoomChange: PropTypes.func,
  // callback for when the user starts panning
  onPanStart: PropTypes.func,
  // callback for when the map stops moving from a pan action
  onPanEnd: PropTypes.func,
  // data test
  dataTest: PropTypes.string,
  // Pose of the robot: {x, y, theta}
  selectedRobotPose: PropTypes.object,
  selectedRobotId: PropTypes.string,
  variant: PropTypes.string
};

export default Map;
export {
  FEATURE_PROPERTY_ANNOTATION_UNIQUE_ID
};
