/**
 * Copyright 2026 InOrbit, Inc.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/**
 * Common interface for Event (Audit) Log. This module receives and records log events.
 * Actual storage of events is delegates to an "event store" instance: 
 * 
 * - dbEventStore stores on the the local database
 * - httpEventStore sends events to a separate service (for larger or specialized deployments)
 *
 * ** THIS MODULE IS SHARED WITH INGEST, DO NOT IMPORT METEOR-ONLY CODE HERE!
 *
 * Events can be any object. Also from this module some constants are exported to annotate
 * events always the same way, including { module, eventType }
 */
// ORO modules
import ThrottledLogger from '../../shared/throttledLogger';
import {
  EventSchemas,
  EVENT_MODULES,
  EVENT_TYPES,
  EVENT_FIELD_MODULE,
  EVENT_FIELD_TYPE,
  getUserLoggingAttributes
} from '../../lib/events';


// Validators for all event types - used only in buildEvent
const EVENT_VALIDATORS = {
  [EVENT_MODULES.LOCK]: EventSchemas.LockEvent,
  [EVENT_MODULES.ACTION]: EventSchemas.ActionEvent,
  [EVENT_MODULES.INCIDENT]: EventSchemas.IncidentEvent,
  [EVENT_MODULES.ALERT]: EventSchemas.AlertEvent,
  [EVENT_MODULES.SETTING]: EventSchemas.SettingEvent,
  [EVENT_MODULES.COLLECTION]: EventSchemas.CollectionEvent,
  [EVENT_MODULES.MISSION]: EventSchemas.MissionEvent,
  [EVENT_MODULES.TRAFFIC_MANAGEMENT]: EventSchemas.TrafficManagementZoneEvent,
};

/**
 * Convenience method to build event objects, which should always have a `module` as source
 * and an `eventType` -- the rest is a freeform object, `data`.
 */
const buildEvent = (module, type, data) => {
  const event = {
    [EVENT_FIELD_MODULE]: module,
    [EVENT_FIELD_TYPE]: type,
    ...data
  };
  try {
    const schema = EVENT_VALIDATORS[module];
    if (!schema) {
      console.error('Unrecognized event module: ' + module, event);
      return null;
    }
    schema.validate(event);
    return event;
  } catch (error) {
    console.error('Failed validation of event', error);
    return null;
  }
};

let instance;
export default class EventLog {
  constructor() {
    // Singleton Pattern
    if (instance === undefined) {
      instance = this;
    }
    // eslint-disable-next-line no-constructor-return
    return instance;
  }

  /**
   * Starts the event log queue..
   */
  init = ({
    eventStore
  }) => {
    if (!eventStore) {
      console.error('EventLogger constructed without an event store!');
    }
    this._store = eventStore;
    this._logger = new ThrottledLogger({});
  };

  /**
   * Shutdown for the module. Sends any pending events and stop accepting further calls.
   */
  shutdown = async () => {
    await this._store.shutdown();
  };

  /**
   * Stores an already-built event (see `buildEvent`). Used for one-off event types such as
   * `action.failed` that have no dedicated logger method.
   * @param {object} event
   */
  sendEvent = (event) => {
    this._store?.storeEvent(event);
  };

  /**
   * Logs all actions that are executed through the actions module.
   * @param {string} robotId An id that univocally identifies a robot.
   * @param {object} action Contains the main info about the action to be logged.
   * @param {string} userId Used to link the action to a given user.
   * @param {object} userProfile Used to link the action to a given user.
   * @param {object} extraParams Contains complementary info about the action to be logged.
   */
  logExecutedAction = async (robot, action, user, extraParams) => {
    try {
      const ts = Date.now();
      const loggedAction = {};
      Object.assign(loggedAction, action);
      Object.assign(loggedAction, extraParams);
      this._store?.storeEvent(buildEvent(EVENT_MODULES.ACTION, EVENT_TYPES.ACTION_EXECUTED, {
        ...getUserLoggingAttributes(user),
        robotId: robot._id,
        robotName: await robot.getNameAsync(),
        ts,
        // EVENT_MODULES.ACTION specific fields
        actionId: loggedAction.actionId,
        type: loggedAction.type,
        label: loggedAction.label,
        action: loggedAction
      }));
    } catch (e) {
      this._logger.error('logExecutedAction', `Error logging action: ${e}`)
    }
  };

  /**
   * Logs all incidents generated by the alertsManager module.
   * @param {object} robot Contains info about a robot.
   * @param {string} triggerId Identifies the data source on which the incident has happened.
   * @param {object} event Contains info about the incident to be logged.
   */
  logIncident = async ({
    robot, triggerId, event, ts = Date.now()
  }) => {
    try {
      this._store?.storeEvent(buildEvent(EVENT_MODULES.INCIDENT, EVENT_TYPES.INCIDENT_TRIGGER, {
        robotId: robot._id,
        robotName: await robot.getNameAsync(),
        ts,
        // EVENT_MODULES.INCIDENT specific fields
        triggerId,
        event
      }));
    } catch (e) {
      // We don't want to stop the incident if for some reason
      // the logging fails.
    }
  };

  /**
   * Logs all alerts generated by the alertsManager module.
   * @param {object} robot Contains info about a robot.
   * @param {string} triggerId Identifies the data source on which the alert has happened.
   * @param {object} event Contains info about the alert to be logged.
   */
  logAlert = async ({
    robot, triggerId, event
  }) => {
    try {
      this._store?.storeEvent(buildEvent(EVENT_MODULES.ALERT, EVENT_TYPES.ALERT_TRIGGER, {
        robotId: robot._id,
        robotName: await robot.getNameAsync(),
        ts: Date.now(),
        triggerId,
        event
      }));
    } catch (e) {
      // We don't want to stop the action execution if for some reason
      // the logging fails.
    }
  };

  /**
   * Logs setting changes generated by the various modules that handles them.
   *
   * @param {string} settingGroupName A human readable string that identifies
   *     a settings section. Example: 'Incidents'.
   * @param {string} robotId (optional) The robot id, if this setting applies
   *     to a robot, for example tagging it
   * @param {string} robotName (optional) The robot name, if this setting
   *     applies to a robot (same as robotId)
   * @param {string} eventType Can be one of the options defined
   *     in web/lib/events.js at EVENT_TYPES (prefixed with SETTING_):
   *     e.g. "setting.added", "setting.removed", "setting.updated".
   * @param (object) data Is a module-dependent object with data representing
   *     what was added, modified, deleted; such as a diff of existing and
   *     new settings version.
   */
  logSetting = ({
    settingGroupName, settingName, user, eventType,
    robotId, robotName
  }) => {
    // TODO(herchu) Log this event change in data lake
    const ts = Date.now();
    this._store?.storeEvent(buildEvent(EVENT_MODULES.SETTING, eventType, {
      settingGroupName,
      settingName,
      robotId,
      robotName,
      ts,
      ...getUserLoggingAttributes(user)
    }));
  };

  /**
   * Logs an action on Missions: defining, executing, cancelling, etc.
   *
   * @param {string} user A user doc from mongodb
   * @param {string} robotId (optional) The robot id, if this event applies to a robot (e.g.
   *     executing a mission)
   * @param {string} robotName (optional) The robot name, if this event applies to a robot
   *     (for example when launching a mission) (same as robotId)
   * @param {string} missionId (optional) The id of the mission being launched or cancelled
   * @param {string} missionLabel (optional) The label of the mission being defined, launched,
   *     cancelled, etc.
   * @param {string} eventType Can be one of the options defined
   *     in web/lib/events.js at EVENT_TYPES (prefixed with SETTING_):
   *     e.g. "mission.executed".
   */
  logMission = ({
    user,
    eventType,
    robotId,
    robotName,
    missionId,
    missionLabel
  }) => {
    const ts = Date.now();
    this._store?.storeEvent(buildEvent(EVENT_MODULES.MISSION, eventType, {
      robotId,
      robotName,
      missionId,
      missionLabel,
      ts,
      ...getUserLoggingAttributes(user)
    }));
  };

  /**
   * Logs all events related to traffic management zones.
   *
   * @param {string} eventType The type of zone event (e.g., "zone.entered", "zone.exited").
   * @param {string} zoneId The unique identifier of the zone.
   * @param {string} zoneLabel The human-readable label of the zone.
   * @param {string} zoneState The current state of the zone.
   * @param {string} robotId The ID of the robot associated with the event.
   * @param {string} robotName The name of the robot associated with the event.
   * @param {string[]} robotInZoneIds The IDs of the robots currently in the zone.
   * @param {string[]} robotInZoneNames The names of the robots currently in the zone.
   * @param {number} ts The timestamp of the event (defaults to current time).
   */
  logZoneEvent = ({
    eventType,
    zoneId,
    zoneLabel,
    zoneState,
    robotId,
    robotName,
    robotInZoneIds,
    robotInZoneNames,
    locationLabel,
    ts = Date.now(),
  }) => {
    this._store?.storeEvent(buildEvent(EVENT_MODULES.TRAFFIC_MANAGEMENT, eventType, {
      zoneId,
      zoneLabel,
      zoneState,
      robotId,
      robotName,
      robotInZoneIds,
      robotInZoneNames,
      locationLabel,
      ts,
    }));
  };
}

export {
  EVENT_TYPES,
  EVENT_MODULES,
  EVENT_FIELD_MODULE,
  EVENT_FIELD_TYPE,
  buildEvent,
};
