name: Tests

on:
  push:
  pull_request:
    types:
    - synchronize

jobs:
  test-web:
    name: Web App Tests
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4

      - name: Install Meteor
        run: curl https://install.meteor.com/\?release\=3.4 | sh

      - name: Install dependencies
        working-directory: web/app
        run: meteor npm install
        # uses: actions/cache@v4
        # with:
        #   path: .
        #   key: ${{ hashFiles('**/package-lock.json') }}

      - name: Run tests
        working-directory: web/app
        env:
          MONGO_URL: mongodb://localhost:27017/test
          TEST_CLIENT: "0"
          MOCHA_REPORTER: "xunit"
          SERVER_MOCHA_OUTPUT: "{PWD}/junit_server.xml"
        run: meteor test --once --driver-package meteortesting:mocha reporter=mocha-junit-reporter

      - name: Check file (1)
        run: |
          echo 1
          ls . -l
          echo 2
          ls .. -l
          echo 3
          ls .. -l
          echo 4
          ls web -l
          echo 5
          ls web/app -l

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: web/app/junit_server.xml

      - name: Publish test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: web/app/junit_server.xml
          reporter: java-junit
