name: Tests

on:
  push:
  pull_request:
    # types:
    # - synchronize

jobs:
  test-web:
    name: Web App Tests
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4

      - name: Install Meteor
        run: curl https://install.meteor.com/\?release\=3.4 | sh

      - name: Install dependencies
        working-directory: web/app
        run: meteor npm install
        # TODO Fix this. We should be able to cache Meteor install and NPM packages steps
        # uses: actions/cache@v4
        # with:
        #   path: .meteor/local
        #   key: ${{ hashFiles('**/package-lock.json') }}

      - name: Run tests
        working-directory: web/app
        env:
          MONGO_URL: mongodb://localhost:27017/test
          TEST_CLIENT: "0"
          MOCHA_REPORTER: "xunit"
          SERVER_MOCHA_OUTPUT: "${{ github.workspace }}/junit_server.xml"
        run: meteor test --once --driver-package meteortesting:mocha reporter=mocha-junit-reporter

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-web
          path: junit_server.xml

      - name: Publish test results
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: Test Results
          path: junit_server.xml
          reporter: java-junit

  test-ingest:
    name: Ingest Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # mongo-unit needs libssl1.1
      - name: Install libssl1.1
        run: |
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          rm libssl1.1_1.1.1f-1ubuntu2_amd64.deb

      - name: Install dependencies
        working-directory: ingest
        run: npm i

      - name: Import shared code
        working-directory: ingest
        run: ./import.sh

      - name: Run tests
        working-directory: ingest
        run: npm run test:unit:report

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-ingest
          path: ingest/junit_ingest.xml

      - name: Publish test results
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: Test Results
          path: ingest/junit_ingest.xml
          reporter: java-junit
