name: Tests

on:
  push:
  pull_request:
    # types:
    # - synchronize

jobs:
  test-web:
    name: Web App Tests
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
    env:
      METEOR_RELEASE: '3.4'

    steps:
      - uses: actions/checkout@v6

      # Meteor ------------------------------------------------------------
      - name: Cache Meteor
        id: cache-meteor
        uses: actions/cache@v4
        with:
          path: ~/.meteor
          key: ${{ runner.os }}-meteor-${{ env.METEOR_RELEASE }}
          restore-keys: |
            ${{ runner.os }}-meteor-

      - name: Install Meteor [if not cached]
        if: steps.cache-meteor.outputs.cache-hit != 'true'
        run: curl https://install.meteor.com/\?release\=${{ env.METEOR_RELEASE }} | sh

      - name: Add Meteor to Path [if cached]
        if: steps.cache-meteor.outputs.cache-hit == 'true'
        run: echo "$HOME/.meteor" >> $GITHUB_PATH

      # NPM ---------------------------------------------------------------
      - name: Cache .npm directory
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: app/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies [if not cached]
        working-directory: app
        run: meteor npm ci
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      # Tests --------------------------------------------------------------
      - name: Run tests
        working-directory: app
        env:
          MONGO_URL: mongodb://localhost:27017/test
          TEST_CLIENT: "0"
          MOCHA_REPORTER: "xunit"
          SERVER_MOCHA_OUTPUT: "${{ github.workspace }}/junit_server.xml"
        run: meteor test --once --driver-package meteortesting:mocha reporter=mocha-junit-reporter

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results-web
          path: junit_server.xml

      - name: Publish test results
        if: always()
        uses: dorny/test-reporter@v3
        with:
          name: Test Results
          path: junit_server.xml
          reporter: java-junit

  test-ingest:
    name: Ingest Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      # mongo-unit needs libssl1.1
      - name: Install libssl1.1
        run: |
          wget https://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          rm libssl1.1_1.1.1f-1ubuntu2_amd64.deb

      - name: Install dependencies
        working-directory: ingest
        run: npm i

      - name: Import shared code
        working-directory: ingest
        run: ./import.sh

      - name: Run tests
        working-directory: ingest
        run: npm run test:unit:report

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results-ingest
          path: ingest/junit_ingest.xml

      - name: Publish test results
        if: always()
        uses: dorny/test-reporter@v3
        with:
          name: Test Results
          path: ingest/junit_ingest.xml
          reporter: java-junit
